allowBuilds:
  sharp: true
  esbuild: true
  unrs-resolver: true
  '@parcel/watcher': false
  '@swc/core': false

enablePrePostScripts: true

confirmModulesPurge: false

minimumReleaseAgeExclude:
  - react-hook-form@7.89.0
